### ISSUE TITLE
Dropdown elements not showing.

### ISSUE THREAD

**Issue by jonathamps** [voerro/vue-tagsinput#66]
The dropdown of existing elements is not working because one of the fields is wrong.

The line 52 on the file VoerroTagsInput.vue should be "v-html="tag.value", or the dropdown will keep not working. 

![image](https://user-images.githubusercontent.com/23514627/61022726-850d6d80-a37d-11e9-9255-7cf28f72deba.png)

**Comment by shiwangebuzhidao** [comment]
Even if the demo for dropdown is broken
 https://voerro.github.io/vue-tagsinput/

**Comment by shiwangebuzhidao** [comment]
Could you also fix installation via CDN together with the npm install method? I have seen the #53 bug is fixed via npm but the bug still exist on the CDN version.

**Comment by AlexMordred** [comment]
The dropdown bug is fixed by @jonathamps in #67, I'll release the fix soon.

@shiwangebuzhidao I think I forgot to update the CDN version in the JS file link in the description. Otherwise the CDN is being updated automatically as soon as I publish a new release. You just should grabe the latest version.
