### ISSUE TITLE
How to set initial tags

### ISSUE THREAD

**Issue by GHopperMSK** [voerro/vue-tagsinput#88]
Hi!

I heve a Laravel project. 

`npm i @voerro/vue-tagsinput --save`

Add `Vue.component('tags-input', require('@voerro/vue-tagsinput').default);` to app.js

Add `@import '~@voerro/vue-tagsinput/dist/style.css';` to app.scss

Run `npm run dev`

Add 
```
...
            <div class="form-group">
                <label for="tags">Тэги</label>
                <tags-input element-id="tags"
                    wrapper-class='form-control'
                    :existing-tags="[
                    @foreach ($tags as $tag)
                        { key: '{{ $tag->id }}', value: '{{ $tag->name }}' },
                    @endforeach
                    ]"
                    :typeahead="true"></tags-input>
            </div>
...
```
to my template file.

So, everything fine until the point! 

Now, what I want to do is to set initial tags to the field. What should I do to achieve this goal?

**Comment by GHopperMSK** [comment]
```
            <div class="form-group">
                <label for="tags">Тэги</label>
                <tags-input element-id="tags"
                    wrapper-class='form-control'
                    :value="[
                        @if (old('tags'))
                            @foreach (json_decode(old('tags')) as $tag)
                                { key: '{{ $tag->key }}', value: '{{ $tag->value }}' },
                            @endforeach
                        @else
                            @foreach ($itemTags as $tag)
                                { key: '{{ $tag->id }}', value: '{{ $tag->name }}' },
                            @endforeach
                        @endif
                    ]"
                    :existing-tags="[
                        @foreach ($allTags as $tag)
                            { key: '{{ $tag->id }}', value: '{{ $tag->name }}' },
                        @endforeach
                    ]"
                    :typeahead="true"></tags-input>
            </div>
```

**Comment by AlexMordred** [comment]
@GHopperMSK Seems like you've solved (almost?) your problem yourself? The only thing you should probably do is to move all that logic to the backend, prepare your `$tags` collection in the required format there. Take a look at this: https://laravel.com/docs/6.x/collections#method-map

**Comment by GHopperMSK** [comment]
I think you should add this case to the docs, due to it  is common practice and it isn't clear at the very start.

**Comment by AlexMordred** [comment]
There's a section called `Setting Selected Tags Programmatically`.

**Comment by Synchro** [comment]
I was confused by this too, largely because I would not describe this as setting tags programatically! I'd reserve that for setting tags from JS code *after* the page has loaded. It doesn't help that the critical `value` property is not documented or even mentioned in the docs, and @GHopperMSK's helpful comment is what I needed to have it work at all. The docs give the impression that the initial values should be put in `existing-tags`, but those seem to be the possible typeahead/autocomplete values, not the initial ones.

On a related note, it's not clear how pre-populating can be done in a progressive-enhancement style, where if JS is disabled, it results in a regular input field containing comma-delimited values.
